include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
    - "**/build/**"
    - "ios/Flutter/**"
    - "android/**"

  errors:
    unrelated_type_equality_checks: error
    unnecessary_nullable_for_final_variable_declarations: warning
    prefer_const_constructors: warning
    use_build_context_synchronously: warning
    deprecated_member_use: warning
    avoid_init_to_null: warning
    inference_failure_on_function_invocation: ignore
    inference_failure_on_instance_creation: ignore
    constant_identifier_names: ignore
    depend_on_referenced_packages: ignore

    deprecated_member_use_from_same_package: warning
    empty_catches: warning
    prefer_if_null_operators: warning

linter:
  rules:
    avoid_print: true
    prefer_relative_imports: false
    always_use_package_imports: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_late: true
    use_super_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    use_key_in_widget_constructors: false
