include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_literals_to_create_immutables: false
    prefer_typing_uninitialized_variables: false
    prefer_const_constructors: false
    file_names: false
    constant_identifier_names: false
    use_build_context_synchronously: false