name: flutter_bump_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  cached_network_image: ^3.4.0
  flutter_bloc: ^8.1.3
  intl: ^0.19.0
  rxdart: ^0.27.7
  permission_handler: ^10.0.1
  json_annotation: ^4.3.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.0
  flutter_secure_storage: ^8.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  path: ^1.8.2
  flutter_easyloading: ^3.0.5
  device_info_plus: ^9.0.2
  jiffy: ^6.2.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.5
  url_launcher: ^6.1.14
  loadmore: ^2.1.0
  uuid: ^4.2.2
  easy_localization: ^3.0.7
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  injectable: ^2.4.2
  dartx: ^1.2.0
  auto_route: ^8.3.0
  vector_graphics: ^1.1.11+1
  path_drawing: ^1.0.1
  device_apps: ^2.2.0
  # hive: ^4.0.0
  # isar_flutter_libs: ^4.0.0-dev.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: any
  build_runner: any
  retrofit_generator: 8.1.2
  flutter_gen_runner: ^5.6.0
  auto_route_generator: ^8.1.0
  injectable_generator: ^2.6.2
  # hive_flutter: ^4.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/lang/

flutter_gen:
  integrations:
    flutter_svg: true